# Generated by Django 2.1.5 on 2020-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('Dewey', models.CharField(max_length=20)),
                ('Titolo', models.CharField(max_length=200)),
                ('Isbn', models.IntegerField()),
                ('Nedizione', models.IntegerField()),
                ('AnnoPubblicazione', models.IntegerField()),
                ('Prezzo', models.IntegerField()),
                ('DataAcquisto', models.DateTimeField(auto_now=True)),
                ('Descrizione', models.CharField(max_length=2000)),
                ('Pagine', models.IntegerField()),
                ('InPrestito', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'verbose_name_plural': 'LIBRI',
            },
        ),
    ]
