# Generated by Django 2.1.5 on 2020-04-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0002_auto_20200406_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
